SIM-000 - end-to-end step v1.1 - yaml aligment

diff --git a/SIDI/steps/_e2e_generate_console_reports/codemagic/step.yml b/SIDI/steps/_e2e_generate_console_reports/codemagic/step.yml
--- a/SIDI/steps/_e2e_generate_console_reports/codemagic/step.yml
+++ b/SIDI/steps/_e2e_generate_console_reports/codemagic/step.yml
@@ -1,88 +1,88 @@
-    name: "[END-TO-END] Console reports"
-    script: |
-      #!/usr/bin/env bash
-      set -e
+name: "[END-TO-END] Console reports"
+script: |
+  #!/usr/bin/env bash
+  set -e
 
-      if [[ "$END_TO_END_COLLECT_ARTIFACTS" != "" ]]; then
-          # Navigate to the end-to-end directory
-          echo "ℹ️ Navigating to the end-to-end directory..."
-          if ! cd ./end-to-end/; then
-              echo "🚨 Failed to navigate to the end-to-end directory."
-              exit 1
-          fi
-
-          # Function to print a row with borders
-          print_row() {
-              local line="$1"
-              printf "| %-12s | %-6s | %-5s | %-6s | %-8s | %-10s |\n" $line
-          }
-
-          # Function to print a border line
-          print_border() {
-              printf "+--------------+--------+-------+--------+----------+------------+\n"
-          }
-
-          # Function to process a folder and extract stats from JSON files
-          process_folder() {
-              local base_path="$1"
-              echo "ℹ️ Processing folder: $base_path" 1>&2
-
-              local table=()
-              local team_name file_to_merge file_content suites tests passes failures perc_success
-
-              print_border
-              print_row "Team" "Suites" "Tests" "Passes" "Failures" "% Success"
-              print_border
-
-              for dir in "$base_path"/*; do
-                  if [[ -d "$dir" ]]; then
-                      team_name=$(basename "$dir" | tr 'a-z' 'A-Z')
-
-                      # Skip if directory is "teams"
-                      if [[ "$team_name" == "TEAMS" ]]; then
-                          continue
-                      fi
-
-                      file_to_merge="$dir/merged-report.json"
-                      if [[ -f "$file_to_merge" ]]; then
-                          # Parse JSON content using jq
-                          if metrics=$(jq -r '.metrics' "$file_to_merge" 2>/dev/null); then
-                              suites=$(jq '.suites | length' "$file_to_merge")
-                              passes=$(jq '.passed' <<< "$metrics")
-                              failures=$(jq '.failed' <<< "$metrics")
-                              skipped=$(jq '.skipped' <<< "$metrics")
-                              # tests=$((passes + failures + skipped))
-                              tests=$((passes + failures))
-
-                              if [[ "$tests" -eq 0 ]]; then
-                                  perc_success="0.00"
-                              else
-                                  perc_success=$(awk "BEGIN {printf \"%.2f\", ($passes/$tests)*100}")
-                              fi
-
-                              print_row "$team_name" "$suites" "$tests" "$passes" "$failures" "$perc_success%"
-                          else
-                              echo "⚠️ Failed to process JSON file: $file_to_merge. Adding error row." 1>&2
-                              print_row "$team_name" "JSON ERROR" "JSON ERROR" "JSON ERROR" "JSON ERROR" "JSON ERROR"
-                          fi
-                      else
-                          echo "🚨 File not found: $file_to_merge" 1>&2
-                          print_row "$team_name" "ERROR" "ERROR" "ERROR" "ERROR" "ERROR"
-                      fi
-                  fi
-              done
-
-              print_border
-          }
-
-          # Main script execution
-          REPORTS_BASE_PATH="build/reports/wdio-html-nice-reporter-reports"
-
-          echo "ℹ️ Processing main folders..."
-          process_folder "$REPORTS_BASE_PATH"
-
-          echo "ℹ️ Processing team folders..."
-          process_folder "$REPORTS_BASE_PATH/teams"
-
-          cd ../
+  if [[ "$END_TO_END_COLLECT_ARTIFACTS" != "" ]]; then
+      # Navigate to the end-to-end directory
+      echo "ℹ️ Navigating to the end-to-end directory..."
+      if ! cd ./end-to-end/; then
+          echo "🚨 Failed to navigate to the end-to-end directory."
+          exit 1
       fi
+
+      # Function to print a row with borders
+      print_row() {
+          local line="$1"
+          printf "| %-12s | %-6s | %-5s | %-6s | %-8s | %-10s |\n" $line
+      }
+
+      # Function to print a border line
+      print_border() {
+          printf "+--------------+--------+-------+--------+----------+------------+\n"
+      }
+
+      # Function to process a folder and extract stats from JSON files
+      process_folder() {
+          local base_path="$1"
+          echo "ℹ️ Processing folder: $base_path" 1>&2
+
+          local table=()
+          local team_name file_to_merge file_content suites tests passes failures perc_success
+
+          print_border
+          print_row "Team" "Suites" "Tests" "Passes" "Failures" "% Success"
+          print_border
+
+          for dir in "$base_path"/*; do
+              if [[ -d "$dir" ]]; then
+                  team_name=$(basename "$dir" | tr 'a-z' 'A-Z')
+
+                  # Skip if directory is "teams"
+                  if [[ "$team_name" == "TEAMS" ]]; then
+                      continue
+                  fi
+
+                  file_to_merge="$dir/merged-report.json"
+                  if [[ -f "$file_to_merge" ]]; then
+                      # Parse JSON content using jq
+                      if metrics=$(jq -r '.metrics' "$file_to_merge" 2>/dev/null); then
+                          suites=$(jq '.suites | length' "$file_to_merge")
+                          passes=$(jq '.passed' <<< "$metrics")
+                          failures=$(jq '.failed' <<< "$metrics")
+                          skipped=$(jq '.skipped' <<< "$metrics")
+                          # tests=$((passes + failures + skipped))
+                          tests=$((passes + failures))
+
+                          if [[ "$tests" -eq 0 ]]; then
+                              perc_success="0.00"
+                          else
+                              perc_success=$(awk "BEGIN {printf \"%.2f\", ($passes/$tests)*100}")
+                          fi
+
+                          print_row "$team_name" "$suites" "$tests" "$passes" "$failures" "$perc_success%"
+                      else
+                          echo "⚠️ Failed to process JSON file: $file_to_merge. Adding error row." 1>&2
+                          print_row "$team_name" "JSON ERROR" "JSON ERROR" "JSON ERROR" "JSON ERROR" "JSON ERROR"
+                      fi
+                  else
+                      echo "🚨 File not found: $file_to_merge" 1>&2
+                      print_row "$team_name" "ERROR" "ERROR" "ERROR" "ERROR" "ERROR"
+                  fi
+              fi
+          done
+
+          print_border
+      }
+
+      # Main script execution
+      REPORTS_BASE_PATH="build/reports/wdio-html-nice-reporter-reports"
+
+      echo "ℹ️ Processing main folders..."
+      process_folder "$REPORTS_BASE_PATH"
+
+      echo "ℹ️ Processing team folders..."
+      process_folder "$REPORTS_BASE_PATH/teams"
+
+      cd ../
+  fi
diff --git a/SIDI/steps/_e2e_install/codemagic/step.yml b/SIDI/steps/_e2e_install/codemagic/step.yml
--- a/SIDI/steps/_e2e_install/codemagic/step.yml
+++ b/SIDI/steps/_e2e_install/codemagic/step.yml
@@ -1,14 +1,14 @@
-    name: "[END-TO-END] Yarn install"
-    script: |
-      #!/usr/bin/env bash
-      set -e
+name: "[END-TO-END] Yarn install"
+script: |
+  #!/usr/bin/env bash
+  set -e
 
-      # Navigate to the end-to-end directory
-      echo "ℹ️ Navigating to the end-to-end directory..."
-      if ! cd ./end-to-end/; then
-        echo "🚨 Failed to navigate to the end-to-end directory."
-        exit 1
-      fi
-      yarn install
-      echo "✅ Yarn install is successfully"
-      cd ../
+  # Navigate to the end-to-end directory
+  echo "ℹ️ Navigating to the end-to-end directory..."
+  if ! cd ./end-to-end/; then
+    echo "🚨 Failed to navigate to the end-to-end directory."
+    exit 1
+  fi
+  yarn install
+  echo "✅ Yarn install is successfully"
+  cd ../
diff --git a/SIDI/steps/_e2e_launch_browserstack_builds/codemagic/step.yml b/SIDI/steps/_e2e_launch_browserstack_builds/codemagic/step.yml
--- a/SIDI/steps/_e2e_launch_browserstack_builds/codemagic/step.yml
+++ b/SIDI/steps/_e2e_launch_browserstack_builds/codemagic/step.yml
@@ -1,138 +1,138 @@
-    name: "[END-TO-END] Run BrowserStack builds"
-    ignore_failure: true
-    script: |
-      #!/usr/bin/env bash
-      # fail if any commands fail
-      set -ex
+name: "[END-TO-END] Run BrowserStack builds"
+ignore_failure: true
+script: |
+  #!/usr/bin/env bash
+  # fail if any commands fail
+  set -ex
 
-      # Run end-to-end tests if required
-      if [[ -n "$RUN_END_TO_END" ]]; then
+  # Run end-to-end tests if required
+  if [[ -n "$RUN_END_TO_END" ]]; then
 
-        # Navigate to the end-to-end directory
-        echo "ℹ️ Navigating to the end-to-end directory..."
-        if ! cd ./end-to-end/; then
-          echo "🚨 Failed to navigate to the end-to-end directory."
-          exit 1
+    # Navigate to the end-to-end directory
+    echo "ℹ️ Navigating to the end-to-end directory..."
+    if ! cd ./end-to-end/; then
+      echo "🚨 Failed to navigate to the end-to-end directory."
+      exit 1
+    fi
+
+    # Determine WDIO config path
+    WDIO_CONFIG_PATH="${WDIO_CONFIG_PATH_IOS:-$WDIO_CONFIG_PATH_ANDROID}"
+
+    if [[ "$END_TO_END_BROWSERSTACK_LOCAL_MODE" == "true" ]]; then
+        # Setup BrowserStack Local
+        BROWSERSTACK_LOCAL_PATH="./build/BrowserStackLocal"
+        if [[ ! -f "$BROWSERSTACK_LOCAL_PATH" ]]; then
+          curl -o ./build/BrowserStackLocal.zip "https://www.browserstack.com/browserstack-local/BrowserStackLocal-darwin-x64.zip"
+          unzip -q ./build/BrowserStackLocal.zip -d "build"
+          rm -f ./build/BrowserStackLocal.zip
         fi
 
-        # Determine WDIO config path
-        WDIO_CONFIG_PATH="${WDIO_CONFIG_PATH_IOS:-$WDIO_CONFIG_PATH_ANDROID}"
+        # Ensure BrowserStack Local is running
+        WDIO_LOCAL_IDENTIFIER="$END_TO_END_BROWSERSTACK_LOCAL_TOKEN+$PROJECT_BUILD_NUMBER"
+        echo "WDIO_LOCAL_IDENTIFIER=$WDIO_LOCAL_IDENTIFIER" >> $CM_ENV
+        echo `pwd`./build/BrowserStackLocal --key $BROWSERSTACKLOCAL_TOKEN --local-identifier $WDIO_LOCAL_IDENTIFIER > build/temp.command; chmod +x build/temp.command; open build/temp.command
+        # the sleep allow the script to have time to start in the new cli
+        sleep 2
+        rm -rf build/temp.command
+        echo "✅ BrowserStackLocal is launched."
+    fi
 
-        if [[ "$END_TO_END_BROWSERSTACK_LOCAL_MODE" == "true" ]]; then
-            # Setup BrowserStack Local
-            BROWSERSTACK_LOCAL_PATH="./build/BrowserStackLocal"
-            if [[ ! -f "$BROWSERSTACK_LOCAL_PATH" ]]; then
-              curl -o ./build/BrowserStackLocal.zip "https://www.browserstack.com/browserstack-local/BrowserStackLocal-darwin-x64.zip"
-              unzip -q ./build/BrowserStackLocal.zip -d "build"
-              rm -f ./build/BrowserStackLocal.zip
-            fi
-
-            # Ensure BrowserStack Local is running
-            WDIO_LOCAL_IDENTIFIER="$END_TO_END_BROWSERSTACK_LOCAL_TOKEN+$PROJECT_BUILD_NUMBER"
-            echo "WDIO_LOCAL_IDENTIFIER=$WDIO_LOCAL_IDENTIFIER" >> $CM_ENV
-            echo `pwd`./build/BrowserStackLocal --key $BROWSERSTACKLOCAL_TOKEN --local-identifier $WDIO_LOCAL_IDENTIFIER > build/temp.command; chmod +x build/temp.command; open build/temp.command
-            # the sleep allow the script to have time to start in the new cli
-            sleep 2
-            rm -rf build/temp.command
-            echo "✅ BrowserStackLocal is launched."
-        fi
-
-        # Ensure required variables are set
-        required_vars=("WDIO_CONFIG_SPECS" "WDIO_CONFIG_PATH" "BROWSERSTACK_APP_URL" "WDIO_CONFIG_REPORT_NAME")
-        for var in "${required_vars[@]}"; do
-            if [ -z "${!var}" ]; then
-                echo "🚨 Error: Environment variable $var is not set."
-                exit 1
-            fi
-        done
-
-        # Process WDIO_CONFIG_SPECS
-        WDIO_CONFIG_SPECS_CORRECT_PATH=$(echo "$WDIO_CONFIG_SPECS" | sed "s/'\\(\\*\\*\\/[^']*\\)'/path.resolve(cleanedPath, '\\1')/g")
-
-        # Determine PLATFORM
-        PLATFORM=${WDIO_CONFIG_PATH_IOS:+ios}
-        PLATFORM=${PLATFORM:-android}
-
-        # Update WDIO_CONFIG_PATH
-        if [[ -f "$WDIO_CONFIG_PATH" ]]; then
-            sed "s#process.env.E2E_SPECS_PATTERN#$WDIO_CONFIG_SPECS_CORRECT_PATH#g" "$WDIO_CONFIG_PATH" > "${WDIO_CONFIG_PATH}.tmp" && mv "${WDIO_CONFIG_PATH}.tmp" "$WDIO_CONFIG_PATH"
-        else
-            echo "🚨 Error: WDIO_CONFIG_PATH ($WDIO_CONFIG_PATH) not found."
+    # Ensure required variables are set
+    required_vars=("WDIO_CONFIG_SPECS" "WDIO_CONFIG_PATH" "BROWSERSTACK_APP_URL" "WDIO_CONFIG_REPORT_NAME")
+    for var in "${required_vars[@]}"; do
+        if [ -z "${!var}" ]; then
+            echo "🚨 Error: Environment variable $var is not set."
             exit 1
         fi
+    done
 
-        # Define updates for .env.remote
-        env_updates=(
-            "BS_PATH=$BROWSERSTACK_APP_URL"
-            "BUILD_URL=https://codemagic.io/app/$CM_PROJECT_ID/build/$CM_BUILD_ID"
-            "BUILD_BRANCH=$CM_BRANCH"
-            "BUILD_NUMBER=$PROJECT_BUILD_NUMBER"
-            "TEAM_NAME=$WDIO_CONFIG_REPORT_NAME"
-            "LOCAL_IDENTIFIER=$WDIO_LOCAL_IDENTIFIER"
-            "PLATFORM=$PLATFORM"
-            "BS_USER=$END_TO_END_BROWSERSTACK_USER_NAME"
-            "BS_KEY=$END_TO_END_BROWSERSTACK_API_TOKEN"
-            "PROJECT_NAME=$CM_REPO_SLUG"
-            "LOCAL_MODE=$END_TO_END_BROWSERSTACK_LOCAL_MODE"
-        )
+    # Process WDIO_CONFIG_SPECS
+    WDIO_CONFIG_SPECS_CORRECT_PATH=$(echo "$WDIO_CONFIG_SPECS" | sed "s/'\\(\\*\\*\\/[^']*\\)'/path.resolve(cleanedPath, '\\1')/g")
 
-        # Update configs/.env.remote
-        for update in "${env_updates[@]}"; do
-            key=$(echo "$update" | cut -d '=' -f 1)
-            value=$(echo "$update" | cut -d '=' -f 2-)
-            sed -i.bak -e "s#${key}=#${key}=${value}#g" configs/.env.remote
-        done
+    # Determine PLATFORM
+    PLATFORM=${WDIO_CONFIG_PATH_IOS:+ios}
+    PLATFORM=${PLATFORM:-android}
 
-        # Cleanup backup files (optional)
-        rm -f configs/.env.remote.bak
+    # Update WDIO_CONFIG_PATH
+    if [[ -f "$WDIO_CONFIG_PATH" ]]; then
+        sed "s#process.env.E2E_SPECS_PATTERN#$WDIO_CONFIG_SPECS_CORRECT_PATH#g" "$WDIO_CONFIG_PATH" > "${WDIO_CONFIG_PATH}.tmp" && mv "${WDIO_CONFIG_PATH}.tmp" "$WDIO_CONFIG_PATH"
+    else
+        echo "🚨 Error: WDIO_CONFIG_PATH ($WDIO_CONFIG_PATH) not found."
+        exit 1
+    fi
 
-        echo "✅ Configuration updated successfully."
+    # Define updates for .env.remote
+    env_updates=(
+        "BS_PATH=$BROWSERSTACK_APP_URL"
+        "BUILD_URL=https://codemagic.io/app/$CM_PROJECT_ID/build/$CM_BUILD_ID"
+        "BUILD_BRANCH=$CM_BRANCH"
+        "BUILD_NUMBER=$PROJECT_BUILD_NUMBER"
+        "TEAM_NAME=$WDIO_CONFIG_REPORT_NAME"
+        "LOCAL_IDENTIFIER=$WDIO_LOCAL_IDENTIFIER"
+        "PLATFORM=$PLATFORM"
+        "BS_USER=$END_TO_END_BROWSERSTACK_USER_NAME"
+        "BS_KEY=$END_TO_END_BROWSERSTACK_API_TOKEN"
+        "PROJECT_NAME=$CM_REPO_SLUG"
+        "LOCAL_MODE=$END_TO_END_BROWSERSTACK_LOCAL_MODE"
+    )
 
-        # Export and execute tests
-        cp "$WDIO_CONFIG_PATH" "$CM_EXPORT_DIR"
-        cp configs/.env.remote "$CM_EXPORT_DIR"
-        set -a
-        source configs/.env.remote
-        set +a
+    # Update configs/.env.remote
+    for update in "${env_updates[@]}"; do
+        key=$(echo "$update" | cut -d '=' -f 1)
+        value=$(echo "$update" | cut -d '=' -f 2-)
+        sed -i.bak -e "s#${key}=#${key}=${value}#g" configs/.env.remote
+    done
 
-        MAX_RETRIES=3
-        RETRY_DELAY=60
-        attempt=0
+    # Cleanup backup files (optional)
+    rm -f configs/.env.remote.bak
 
-        while [[ $attempt -lt $MAX_RETRIES ]]; do
-            ((attempt++))
-            echo "ℹ️ Attempt $attempt of $MAX_RETRIES: Running npx wdio $WDIO_CONFIG_PATH..."
+    echo "✅ Configuration updated successfully."
+
+    # Export and execute tests
+    cp "$WDIO_CONFIG_PATH" "$CM_EXPORT_DIR"
+    cp configs/.env.remote "$CM_EXPORT_DIR"
+    set -a
+    source configs/.env.remote
+    set +a
+
+    MAX_RETRIES=3
+    RETRY_DELAY=60
+    attempt=0
+
+    while [[ $attempt -lt $MAX_RETRIES ]]; do
+        ((attempt++))
+        echo "ℹ️ Attempt $attempt of $MAX_RETRIES: Running npx wdio $WDIO_CONFIG_PATH..."
+        
+        # Run the command and capture its output and exit code
+        output=$(npx wdio "$WDIO_CONFIG_PATH" 2>&1)
+        exit_code=$?
+
+        # Check for the specific timeout error and startWebDriverSession in the logs
+        if echo "$output" | grep -q "WebDriverError: The operation was aborted due to timeout" && echo "$output" | grep -q "startWebDriverSession"; then
+            echo "⚠️ Timeout detected in logs (startWebDriverSession). Retrying in $RETRY_DELAY seconds..."
             
-            # Run the command and capture its output and exit code
-            output=$(npx wdio "$WDIO_CONFIG_PATH" 2>&1)
-            exit_code=$?
+            RESULTS_DIR="./build/reports/wdio-html-nice-reporter-results"
 
-            # Check for the specific timeout error and startWebDriverSession in the logs
-            if echo "$output" | grep -q "WebDriverError: The operation was aborted due to timeout" && echo "$output" | grep -q "startWebDriverSession"; then
-                echo "⚠️ Timeout detected in logs (startWebDriverSession). Retrying in $RETRY_DELAY seconds..."
-                
-                RESULTS_DIR="./build/reports/wdio-html-nice-reporter-results"
-
-                # Check if the directory exists
-                if [[ -d "$RESULTS_DIR" ]]; then
-                    echo "ℹ️ Deleting all files in $RESULTS_DIR..."
-                    rm -f "$RESULTS_DIR"/*
-                    echo "✅ All files in $RESULTS_DIR have been deleted."
-                else
-                    echo "⚠️ Directory $RESULTS_DIR does not exist. No files to delete."
-                fi
-                sleep $RETRY_DELAY
+            # Check if the directory exists
+            if [[ -d "$RESULTS_DIR" ]]; then
+                echo "ℹ️ Deleting all files in $RESULTS_DIR..."
+                rm -f "$RESULTS_DIR"/*
+                echo "✅ All files in $RESULTS_DIR have been deleted."
             else
-                # Exit the loop if no specific error was detected (success or other errors)
-                break
+                echo "⚠️ Directory $RESULTS_DIR does not exist. No files to delete."
             fi
-        done
-
-        if [[ $exit_code -ne 0 ]]; then
-            echo "🚨 Failed after $MAX_RETRIES attempts. Please check logs for details."
-            exit $exit_code
+            sleep $RETRY_DELAY
         else
-            echo "✅ Success on attempt $attempt."
-            exit 0
+            # Exit the loop if no specific error was detected (success or other errors)
+            break
         fi
-      fi
+    done
+
+    if [[ $exit_code -ne 0 ]]; then
+        echo "🚨 Failed after $MAX_RETRIES attempts. Please check logs for details."
+        exit $exit_code
+    else
+        echo "✅ Success on attempt $attempt."
+        exit 0
+    fi
+  fi
diff --git a/SIDI/steps/_e2e_launch_builds/codemagic/step.yml b/SIDI/steps/_e2e_launch_builds/codemagic/step.yml
--- a/SIDI/steps/_e2e_launch_builds/codemagic/step.yml
+++ b/SIDI/steps/_e2e_launch_builds/codemagic/step.yml
@@ -1,124 +1,123 @@
-    name: "[END-TO-END] Launch builds"
-    script: |
-      #!/usr/bin/env bash
-      # fail if any commands fails
-      set -ex
+name: "[END-TO-END] Launch builds"
+script: |
+  #!/usr/bin/env bash
+  # fail if any commands fails
+  set -ex
 
-      res=$(jq -c --arg key "$END_TO_END_CONFIG_KEY" '.[] | select(.config_name == $key) | .config_content' "$END_TO_END_CONFIG_PATH")
-      WDIO_CONFIG_BACKWARD="$(echo "$res" | jq -c -r '.config_backward_compatibility')"
+  res=$(jq -c --arg key "$END_TO_END_CONFIG_KEY" '.[] | select(.config_name == $key) | .config_content' "$END_TO_END_CONFIG_PATH")
+  WDIO_CONFIG_BACKWARD="$(echo "$res" | jq -c -r '.config_backward_compatibility')"
 
-      # Check if we are in backward compatibility mode
-      if [[ "$CM_WORKFLOW_NAME" != "" && "$CM_WORKFLOW_NAME" == *"backward_compatibility"* ]]; then
-          echo "Backward compatibility mode"
-          echo $WDIO_CONFIG_BACKWARD
-          echo $CM_WORKFLOW_NAME
-          APP_VERSION="$WDIO_CONFIG_BACKWARD"
-          echo "APP_VERSION=$APP_VERSION" >> $CM_ENV
-      else
-          # FIXME: Force APP_VERSION instead of using check versioned branch
-          echo "Regular mode"
-          APP_VERSION="${CM_BRANCH##*/}"
-          echo "APP_VERSION=$APP_VERSION" >> $CM_ENV
-      fi
+  # Check if we are in backward compatibility mode
+  if [[ "$CM_WORKFLOW_NAME" != "" && "$CM_WORKFLOW_NAME" == *"backward_compatibility"* ]]; then
+      echo "Backward compatibility mode"
+      echo $WDIO_CONFIG_BACKWARD
+      echo $CM_WORKFLOW_NAME
+      APP_VERSION="$WDIO_CONFIG_BACKWARD"
+      echo "APP_VERSION=$APP_VERSION" >> $CM_ENV
+  else
+      # FIXME: Force APP_VERSION instead of using check versioned branch
+      echo "Regular mode"
+      APP_VERSION="${CM_BRANCH##*/}"
+      echo "APP_VERSION=$APP_VERSION" >> $CM_ENV
+  fi
 
-      SLEEP_BTW_LAUNCH=5
+  SLEEP_BTW_LAUNCH=5
 
-      # Add results of E2E into $CM_EXPORT_DIR
-      if [[ "$WDIO_CONFIG_1_REPORT_NAME" != "" ]]; then
-            echo "========================================="
-            echo "[END-TO-END] Start iOS lane 1 "
-            echo "========================================="
+  # Add results of E2E into $CM_EXPORT_DIR
+  if [[ "$WDIO_CONFIG_1_REPORT_NAME" != "" ]]; then
+        echo "========================================="
+        echo "[END-TO-END] Start iOS lane 1 "
+        echo "========================================="
 
-            IOS_BUILD_SLUG_1=$(curl -H "Content-Type: application/json" -H "x-auth-token: $CODE_MAGIC_TOKEN" --data "{ \"appId\": \"$CM_PROJECT_ID\", \"workflowId\": \"build_e2e_ios\", \"branch\": \"$CM_BRANCH\", \"environment\": { \"variables\": { \"RUN_END_TO_END\":\"$RUN_END_TO_END\", \"END_TO_END_CONFIG_KEY\":\"$END_TO_END_CONFIG_KEY\", \"E2E_APP_VERSION\":\"$APP_VERSION\", \"WDIO_CONFIG_1_REPORT_NAME\":\"$WDIO_CONFIG_1_REPORT_NAME\", \"WDIO_CONFIG_1_SPECS_NAME\":\"$WDIO_CONFIG_1_SPECS_NAME\", \"WDIO_CONFIG_PATH_IOS\":\"$WDIO_CONFIG_PATH_IOS\" }}}" https://api.codemagic.io/builds | jq '.buildId' | sed 's/"//g')
-            echo "IOS_BUILD_SLUG_1=$IOS_BUILD_SLUG_1" >> $CM_ENV
+        IOS_BUILD_SLUG_1=$(curl -H "Content-Type: application/json" -H "x-auth-token: $CODE_MAGIC_TOKEN" --data "{ \"appId\": \"$CM_PROJECT_ID\", \"workflowId\": \"build_e2e_ios\", \"branch\": \"$CM_BRANCH\", \"environment\": { \"variables\": { \"RUN_END_TO_END\":\"$RUN_END_TO_END\", \"END_TO_END_CONFIG_KEY\":\"$END_TO_END_CONFIG_KEY\", \"E2E_APP_VERSION\":\"$APP_VERSION\", \"WDIO_CONFIG_1_REPORT_NAME\":\"$WDIO_CONFIG_1_REPORT_NAME\", \"WDIO_CONFIG_1_SPECS_NAME\":\"$WDIO_CONFIG_1_SPECS_NAME\", \"WDIO_CONFIG_PATH_IOS\":\"$WDIO_CONFIG_PATH_IOS\" }}}" https://api.codemagic.io/builds | jq '.buildId' | sed 's/"//g')
+        echo "IOS_BUILD_SLUG_1=$IOS_BUILD_SLUG_1" >> $CM_ENV
 
-            echo "========================================="
-            echo "[END-TO-END] Start Android lane 1 "
-            echo "========================================="
+        echo "========================================="
+        echo "[END-TO-END] Start Android lane 1 "
+        echo "========================================="
 
-            # Limit spam to CodeMagic API and Git provider
-            sleep $SLEEP_BTW_LAUNCH
-            ANDROID_BUILD_SLUG_1=$(curl -H "Content-Type: application/json" -H "x-auth-token: $CODE_MAGIC_TOKEN" --data "{ \"appId\": \"$CM_PROJECT_ID\", \"workflowId\": \"build_e2e_android\", \"branch\": \"$CM_BRANCH\", \"environment\": { \"variables\": { \"RUN_END_TO_END\":\"$RUN_END_TO_END\", \"END_TO_END_CONFIG_KEY\":\"$END_TO_END_CONFIG_KEY\", \"E2E_APP_VERSION\":\"$APP_VERSION\", \"WDIO_CONFIG_1_REPORT_NAME\":\"$WDIO_CONFIG_1_REPORT_NAME\", \"WDIO_CONFIG_1_SPECS_NAME\":\"$WDIO_CONFIG_1_SPECS_NAME\", \"WDIO_CONFIG_PATH_ANDROID\":\"$WDIO_CONFIG_PATH_ANDROID\" }}}" https://api.codemagic.io/builds | jq '.buildId' | sed 's/"//g')
-            echo "ANDROID_BUILD_SLUG_1=$ANDROID_BUILD_SLUG_1" >> $CM_ENV
-      fi
+        # Limit spam to CodeMagic API and Git provider
+        sleep $SLEEP_BTW_LAUNCH
+        ANDROID_BUILD_SLUG_1=$(curl -H "Content-Type: application/json" -H "x-auth-token: $CODE_MAGIC_TOKEN" --data "{ \"appId\": \"$CM_PROJECT_ID\", \"workflowId\": \"build_e2e_android\", \"branch\": \"$CM_BRANCH\", \"environment\": { \"variables\": { \"RUN_END_TO_END\":\"$RUN_END_TO_END\", \"END_TO_END_CONFIG_KEY\":\"$END_TO_END_CONFIG_KEY\", \"E2E_APP_VERSION\":\"$APP_VERSION\", \"WDIO_CONFIG_1_REPORT_NAME\":\"$WDIO_CONFIG_1_REPORT_NAME\", \"WDIO_CONFIG_1_SPECS_NAME\":\"$WDIO_CONFIG_1_SPECS_NAME\", \"WDIO_CONFIG_PATH_ANDROID\":\"$WDIO_CONFIG_PATH_ANDROID\" }}}" https://api.codemagic.io/builds | jq '.buildId' | sed 's/"//g')
+        echo "ANDROID_BUILD_SLUG_1=$ANDROID_BUILD_SLUG_1" >> $CM_ENV
+  fi
 
-      if [[ "$WDIO_CONFIG_2_REPORT_NAME" != "" ]]; then
-            echo "========================================="
-            echo "[END-TO-END] Start iOS lane 2 "
-            echo "========================================="
+  if [[ "$WDIO_CONFIG_2_REPORT_NAME" != "" ]]; then
+        echo "========================================="
+        echo "[END-TO-END] Start iOS lane 2 "
+        echo "========================================="
 
-            # Limit spam to CodeMagic API and Git provider
-            sleep $SLEEP_BTW_LAUNCH
-            IOS_BUILD_SLUG_2=$(curl -H "Content-Type: application/json" -H "x-auth-token: $CODE_MAGIC_TOKEN" --data "{ \"appId\": \"$CM_PROJECT_ID\", \"workflowId\": \"build_e2e_ios\", \"branch\": \"$CM_BRANCH\", \"environment\": { \"variables\": { \"RUN_END_TO_END\":\"$RUN_END_TO_END\", \"END_TO_END_CONFIG_KEY\":\"$END_TO_END_CONFIG_KEY\", \"E2E_APP_VERSION\":\"$APP_VERSION\", \"WDIO_CONFIG_2_REPORT_NAME\":\"$WDIO_CONFIG_2_REPORT_NAME\", \"WDIO_CONFIG_2_SPECS_NAME\":\"$WDIO_CONFIG_2_SPECS_NAME\", \"WDIO_CONFIG_PATH_IOS\":\"$WDIO_CONFIG_PATH_IOS\" }}}" https://api.codemagic.io/builds | jq '.buildId' | sed 's/"//g')
-            echo "IOS_BUILD_SLUG_2=$IOS_BUILD_SLUG_2" >> $CM_ENV
+        # Limit spam to CodeMagic API and Git provider
+        sleep $SLEEP_BTW_LAUNCH
+        IOS_BUILD_SLUG_2=$(curl -H "Content-Type: application/json" -H "x-auth-token: $CODE_MAGIC_TOKEN" --data "{ \"appId\": \"$CM_PROJECT_ID\", \"workflowId\": \"build_e2e_ios\", \"branch\": \"$CM_BRANCH\", \"environment\": { \"variables\": { \"RUN_END_TO_END\":\"$RUN_END_TO_END\", \"END_TO_END_CONFIG_KEY\":\"$END_TO_END_CONFIG_KEY\", \"E2E_APP_VERSION\":\"$APP_VERSION\", \"WDIO_CONFIG_2_REPORT_NAME\":\"$WDIO_CONFIG_2_REPORT_NAME\", \"WDIO_CONFIG_2_SPECS_NAME\":\"$WDIO_CONFIG_2_SPECS_NAME\", \"WDIO_CONFIG_PATH_IOS\":\"$WDIO_CONFIG_PATH_IOS\" }}}" https://api.codemagic.io/builds | jq '.buildId' | sed 's/"//g')
+        echo "IOS_BUILD_SLUG_2=$IOS_BUILD_SLUG_2" >> $CM_ENV
 
-            echo "========================================="
-            echo "[END-TO-END] Start Android lane 2 "
-            echo "========================================="
+        echo "========================================="
+        echo "[END-TO-END] Start Android lane 2 "
+        echo "========================================="
 
-            # Limit spam to CodeMagic API and Git provider
-            sleep $SLEEP_BTW_LAUNCH
-            ANDROID_BUILD_SLUG_2=$(curl -H "Content-Type: application/json" -H "x-auth-token: $CODE_MAGIC_TOKEN" --data "{ \"appId\": \"$CM_PROJECT_ID\", \"workflowId\": \"build_e2e_android\", \"branch\": \"$CM_BRANCH\", \"environment\": { \"variables\": { \"RUN_END_TO_END\":\"$RUN_END_TO_END\", \"END_TO_END_CONFIG_KEY\":\"$END_TO_END_CONFIG_KEY\", \"E2E_APP_VERSION\":\"$APP_VERSION\", \"WDIO_CONFIG_2_REPORT_NAME\":\"$WDIO_CONFIG_2_REPORT_NAME\", \"WDIO_CONFIG_2_SPECS_NAME\":\"$WDIO_CONFIG_2_SPECS_NAME\", \"WDIO_CONFIG_PATH_ANDROID\":\"$WDIO_CONFIG_PATH_ANDROID\" }}}" https://api.codemagic.io/builds | jq '.buildId' | sed 's/"//g')
-            echo "ANDROID_BUILD_SLUG_2=$ANDROID_BUILD_SLUG_2" >> $CM_ENV
-      fi
+        # Limit spam to CodeMagic API and Git provider
+        sleep $SLEEP_BTW_LAUNCH
+        ANDROID_BUILD_SLUG_2=$(curl -H "Content-Type: application/json" -H "x-auth-token: $CODE_MAGIC_TOKEN" --data "{ \"appId\": \"$CM_PROJECT_ID\", \"workflowId\": \"build_e2e_android\", \"branch\": \"$CM_BRANCH\", \"environment\": { \"variables\": { \"RUN_END_TO_END\":\"$RUN_END_TO_END\", \"END_TO_END_CONFIG_KEY\":\"$END_TO_END_CONFIG_KEY\", \"E2E_APP_VERSION\":\"$APP_VERSION\", \"WDIO_CONFIG_2_REPORT_NAME\":\"$WDIO_CONFIG_2_REPORT_NAME\", \"WDIO_CONFIG_2_SPECS_NAME\":\"$WDIO_CONFIG_2_SPECS_NAME\", \"WDIO_CONFIG_PATH_ANDROID\":\"$WDIO_CONFIG_PATH_ANDROID\" }}}" https://api.codemagic.io/builds | jq '.buildId' | sed 's/"//g')
+        echo "ANDROID_BUILD_SLUG_2=$ANDROID_BUILD_SLUG_2" >> $CM_ENV
+  fi
 
-      if [[ "$WDIO_CONFIG_3_REPORT_NAME" != "" ]]; then
-            echo "========================================="
-            echo "[END-TO-END] Start iOS lane 3 "
-            echo "========================================="
+  if [[ "$WDIO_CONFIG_3_REPORT_NAME" != "" ]]; then
+        echo "========================================="
+        echo "[END-TO-END] Start iOS lane 3 "
+        echo "========================================="
 
-            # Limit spam to CodeMagic API and Git provider
-            sleep $SLEEP_BTW_LAUNCH
-            IOS_BUILD_SLUG_3=$(curl -H "Content-Type: application/json" -H "x-auth-token: $CODE_MAGIC_TOKEN" --data "{ \"appId\": \"$CM_PROJECT_ID\", \"workflowId\": \"build_e2e_ios\", \"branch\": \"$CM_BRANCH\", \"environment\": { \"variables\": { \"RUN_END_TO_END\":\"$RUN_END_TO_END\", \"END_TO_END_CONFIG_KEY\":\"$END_TO_END_CONFIG_KEY\", \"E2E_APP_VERSION\":\"$APP_VERSION\", \"WDIO_CONFIG_3_REPORT_NAME\":\"$WDIO_CONFIG_3_REPORT_NAME\", \"WDIO_CONFIG_3_SPECS_NAME\":\"$WDIO_CONFIG_3_SPECS_NAME\", \"WDIO_CONFIG_PATH_IOS\":\"$WDIO_CONFIG_PATH_IOS\" }}}" https://api.codemagic.io/builds | jq '.buildId' | sed 's/"//g')
-            echo "IOS_BUILD_SLUG_3=$IOS_BUILD_SLUG_3" >> $CM_ENV
+        # Limit spam to CodeMagic API and Git provider
+        sleep $SLEEP_BTW_LAUNCH
+        IOS_BUILD_SLUG_3=$(curl -H "Content-Type: application/json" -H "x-auth-token: $CODE_MAGIC_TOKEN" --data "{ \"appId\": \"$CM_PROJECT_ID\", \"workflowId\": \"build_e2e_ios\", \"branch\": \"$CM_BRANCH\", \"environment\": { \"variables\": { \"RUN_END_TO_END\":\"$RUN_END_TO_END\", \"END_TO_END_CONFIG_KEY\":\"$END_TO_END_CONFIG_KEY\", \"E2E_APP_VERSION\":\"$APP_VERSION\", \"WDIO_CONFIG_3_REPORT_NAME\":\"$WDIO_CONFIG_3_REPORT_NAME\", \"WDIO_CONFIG_3_SPECS_NAME\":\"$WDIO_CONFIG_3_SPECS_NAME\", \"WDIO_CONFIG_PATH_IOS\":\"$WDIO_CONFIG_PATH_IOS\" }}}" https://api.codemagic.io/builds | jq '.buildId' | sed 's/"//g')
+        echo "IOS_BUILD_SLUG_3=$IOS_BUILD_SLUG_3" >> $CM_ENV
 
-            echo "========================================="
-            echo "[END-TO-END] Start Android lane 3 "
-            echo "========================================="
+        echo "========================================="
+        echo "[END-TO-END] Start Android lane 3 "
+        echo "========================================="
 
-            # Limit spam to CodeMagic API and Git provider
-            sleep $SLEEP_BTW_LAUNCH
-            ANDROID_BUILD_SLUG_3=$(curl -H "Content-Type: application/json" -H "x-auth-token: $CODE_MAGIC_TOKEN" --data "{ \"appId\": \"$CM_PROJECT_ID\", \"workflowId\": \"build_e2e_android\", \"branch\": \"$CM_BRANCH\", \"environment\": { \"variables\": { \"RUN_END_TO_END\":\"$RUN_END_TO_END\", \"END_TO_END_CONFIG_KEY\":\"$END_TO_END_CONFIG_KEY\", \"E2E_APP_VERSION\":\"$APP_VERSION\", \"WDIO_CONFIG_3_REPORT_NAME\":\"$WDIO_CONFIG_3_REPORT_NAME\", \"WDIO_CONFIG_3_SPECS_NAME\":\"$WDIO_CONFIG_3_SPECS_NAME\", \"WDIO_CONFIG_PATH_ANDROID\":\"$WDIO_CONFIG_PATH_ANDROID\" }}}" https://api.codemagic.io/builds | jq '.buildId' | sed 's/"//g')
-            echo "ANDROID_BUILD_SLUG_3=$ANDROID_BUILD_SLUG_3" >> $CM_ENV
-      fi
+        # Limit spam to CodeMagic API and Git provider
+        sleep $SLEEP_BTW_LAUNCH
+        ANDROID_BUILD_SLUG_3=$(curl -H "Content-Type: application/json" -H "x-auth-token: $CODE_MAGIC_TOKEN" --data "{ \"appId\": \"$CM_PROJECT_ID\", \"workflowId\": \"build_e2e_android\", \"branch\": \"$CM_BRANCH\", \"environment\": { \"variables\": { \"RUN_END_TO_END\":\"$RUN_END_TO_END\", \"END_TO_END_CONFIG_KEY\":\"$END_TO_END_CONFIG_KEY\", \"E2E_APP_VERSION\":\"$APP_VERSION\", \"WDIO_CONFIG_3_REPORT_NAME\":\"$WDIO_CONFIG_3_REPORT_NAME\", \"WDIO_CONFIG_3_SPECS_NAME\":\"$WDIO_CONFIG_3_SPECS_NAME\", \"WDIO_CONFIG_PATH_ANDROID\":\"$WDIO_CONFIG_PATH_ANDROID\" }}}" https://api.codemagic.io/builds | jq '.buildId' | sed 's/"//g')
+        echo "ANDROID_BUILD_SLUG_3=$ANDROID_BUILD_SLUG_3" >> $CM_ENV
+  fi
 
-      if [[ ${IOS_BUILD_SLUG_1} != "" && ${IOS_BUILD_SLUG_1} != "EMPTY" ]]; then
-            echo "========================================="
-            echo "[END-TO-END] Complete builds list variable"
-            echo "========================================="
+  if [[ ${IOS_BUILD_SLUG_1} != "" && ${IOS_BUILD_SLUG_1} != "EMPTY" ]]; then
+        echo "========================================="
+        echo "[END-TO-END] Complete builds list variable"
+        echo "========================================="
 
-            # Avoid usage of run_if + don't re-enter in the loop if builds are already added
-            if [ "$RETRIGGER_WAITING_PREVIOUS_BUILDS" == "true" ]
-                  then
-                  echo "Waiting builds to trigger new ones..."
-                  exit 0
-            fi
+        # Avoid usage of run_if + don't re-enter in the loop if builds are already added
+        if [ "$RETRIGGER_WAITING_PREVIOUS_BUILDS" == "true" ]
+              then
+              echo "Waiting builds to trigger new ones..."
+              exit 0
+        fi
 
-            echo "Current END_TO_END_BUILD_LIST:$END_TO_END_BUILD_LIST"
-            L_END_TO_END_BUILD_LIST=$END_TO_END_BUILD_LIST
+        echo "Current END_TO_END_BUILD_LIST:$END_TO_END_BUILD_LIST"
+        L_END_TO_END_BUILD_LIST=$END_TO_END_BUILD_LIST
 
-            echo "Current IOS_BUILD_SLUG_1:$IOS_BUILD_SLUG_1"
-            echo "Current ANDROID_BUILD_SLUG_1:$ANDROID_BUILD_SLUG_1"
+        echo "Current IOS_BUILD_SLUG_1:$IOS_BUILD_SLUG_1"
+        echo "Current ANDROID_BUILD_SLUG_1:$ANDROID_BUILD_SLUG_1"
 
-            # We take in consideration that we always trigger both platform
-            if [[ ${IOS_BUILD_SLUG_1} != "" && ${IOS_BUILD_SLUG_1} != "EMPTY" ]]; then
-                  L_END_TO_END_BUILD_LIST=$L_END_TO_END_BUILD_LIST+$IOS_BUILD_SLUG_1+$ANDROID_BUILD_SLUG_1
-            fi
+        # We take in consideration that we always trigger both platform
+        if [[ ${IOS_BUILD_SLUG_1} != "" && ${IOS_BUILD_SLUG_1} != "EMPTY" ]]; then
+              L_END_TO_END_BUILD_LIST=$L_END_TO_END_BUILD_LIST+$IOS_BUILD_SLUG_1+$ANDROID_BUILD_SLUG_1
+        fi
 
-            if [[ ${IOS_BUILD_SLUG_2} != "" && ${IOS_BUILD_SLUG_2} != "EMPTY" ]]; then
-                  L_END_TO_END_BUILD_LIST=$L_END_TO_END_BUILD_LIST+$IOS_BUILD_SLUG_2+$ANDROID_BUILD_SLUG_2
-            fi
+        if [[ ${IOS_BUILD_SLUG_2} != "" && ${IOS_BUILD_SLUG_2} != "EMPTY" ]]; then
+              L_END_TO_END_BUILD_LIST=$L_END_TO_END_BUILD_LIST+$IOS_BUILD_SLUG_2+$ANDROID_BUILD_SLUG_2
+        fi
 
-            if [[ ${IOS_BUILD_SLUG_3} != "" && ${IOS_BUILD_SLUG_3} != "EMPTY" ]]; then
-                  L_END_TO_END_BUILD_LIST=$L_END_TO_END_BUILD_LIST+$IOS_BUILD_SLUG_3+$ANDROID_BUILD_SLUG_3
-            fi
+        if [[ ${IOS_BUILD_SLUG_3} != "" && ${IOS_BUILD_SLUG_3} != "EMPTY" ]]; then
+              L_END_TO_END_BUILD_LIST=$L_END_TO_END_BUILD_LIST+$IOS_BUILD_SLUG_3+$ANDROID_BUILD_SLUG_3
+        fi
 
-            # Remove char "+" for the first build if any
-            L_END_TO_END_BUILD_LIST=${L_END_TO_END_BUILD_LIST#+}
+        # Remove char "+" for the first build if any
+        L_END_TO_END_BUILD_LIST=${L_END_TO_END_BUILD_LIST#+}
 
-            echo "New END_TO_END_BUILD_LIST:$L_END_TO_END_BUILD_LIST"
+        echo "New END_TO_END_BUILD_LIST:$L_END_TO_END_BUILD_LIST"
 
-            END_TO_END_BUILD_LIST="$L_END_TO_END_BUILD_LIST"
-            echo "END_TO_END_BUILD_LIST=$END_TO_END_BUILD_LIST" >> $CM_ENV
-      fi
- 
+        END_TO_END_BUILD_LIST="$L_END_TO_END_BUILD_LIST"
+        echo "END_TO_END_BUILD_LIST=$END_TO_END_BUILD_LIST" >> $CM_ENV
+  fi
