ARHS-001 - Update from last version

diff --git a/SIDI/steps/_e2e_collect_artifacts/codemagic/step.yml b/SIDI/steps/_e2e_collect_artifacts/codemagic/step.yml
--- a/SIDI/steps/_e2e_collect_artifacts/codemagic/step.yml
+++ b/SIDI/steps/_e2e_collect_artifacts/codemagic/step.yml
@@ -3,7 +3,6 @@ script: |
   #!/usr/bin/env bash
   # fail if any commands fails
   set -e
-
   if [[ "$END_TO_END_COLLECT_ARTIFACTS" != "" ]]; then
         echo "ℹ️ Collects results on builds: $END_TO_END_BUILD_LIST..."
         export IFS="+"
@@ -12,9 +11,9 @@ script: |
         echo "Retrieve from $build_slug... in 10 seconds"
         sleep 10
 
-        # Counter for invalid JSON files
+        # Initialize variables
+        declare -a failed_builds=()
         invalid_json_count=0
-        invalid_builds_count=0
 
         for build_slug in $END_TO_END_BUILD_LIST; do
               # Fetch info about the artifact
@@ -34,15 +33,16 @@ script: |
 
                     # Define a function to validate JSON files
                     validate_json() {
-                        local file="$1"
-                        local invalid_dir="./end-to-end/build/reports/wdio-html-nice-reporter-results-invalid"
-                        if ! jq empty "$file" >/dev/null 2>&1; then
-                            echo "⚠️ Skipped invalid JSON file: $file. This may result in incomplete data in the report." 1>&2
-                            mv "$file" "$invalid_dir/"
-                            ((invalid_json_count++))
-                            return 1
-                        fi
-                        return 0
+                          local file="$1"
+                          local invalid_dir="./end-to-end/build/reports/wdio-html-nice-reporter-results-invalid"
+                          if ! jq empty "$file" >/dev/null 2>&1; then
+                                echo "⚠️ Skipped invalid JSON file: $file. This may result in incomplete data in the report." 1>&2
+                                mv "$file" "$invalid_dir/"
+                                ((invalid_json_count++))
+                                failed_builds+=("$build_slug")
+                                return 1
+                          fi
+                          return 0
                     }
 
                     # Directory containing the JSON files
@@ -50,47 +50,53 @@ script: |
 
                     # Check if the directory exists and contains JSON files
                     if [[ -d "$JSON_DIR" && $(find "$JSON_DIR" -type f -name '*.json' | wc -l) -gt 0 ]]; then
-                        echo "ℹ️ Validating JSON files in $JSON_DIR..." 1>&2
-                        for file in "$JSON_DIR"/*.json; do
-                            if [[ -f "$file" ]]; then
+                          echo "ℹ️ Validating JSON files in $JSON_DIR..." 1>&2
+                          for file in "$JSON_DIR"/*.json; do
+                                if [[ -f "$file" ]]; then
                                 validate_json "$file" || echo "⚠️ File removed: $file due to invalid JSON." 1>&2
-                            fi
-                        done
+                                fi
+                          done
                     else
-                        echo "⚠️ Warning: No JSON files found in $JSON_DIR." 1>&2
-                        ((invalid_builds_count++))
+                          echo "⚠️ Warning: No JSON files found in $JSON_DIR for $build_slug" 1>&2
+                          failed_builds+=("$build_slug")
                     fi
 
                     # remove empty report files to avoid error
                     find ./end-to-end/build/reports/wdio-html-nice-reporter-results -type f -empty -print -delete
               else
                     echo "🚨 No artifacts found for build $build_slug; something goes wrong..."
-                    ((invalid_builds_count++))
+                    failed_builds+=("$build_slug")
               fi
         done
 
+        # Calculate INVALID_BUILDS_COUNT as the size of the failed_builds array
+        INVALID_BUILDS_COUNT=${#failed_builds[@]}
+
+        # Output the failed builds and counts
+        echo "Failed builds: ${failed_builds[*]}"
         echo "INVALID_JSON_COUNT=$invalid_json_count" >> $CM_ENV
-        echo "INVALID_BUILDS_COUNT=$invalid_builds_count" >> $CM_ENV
+        echo "INVALID_BUILDS_COUNT=$INVALID_BUILDS_COUNT" >> $CM_ENV
+        echo "FAILED_BUILDS_LIST=${failed_builds[*]}" >> $CM_ENV
 
         # Read JSON content from the file
-        res=$(jq -c --arg key "$END_TO_END_CONFIG_KEY" '.[] | select(.config_name == $key) | .config_content' "$END_TO_END_CONFIG_PATH")
+        res=$(jq -c --arg key "$END_TO_END_CONFIG_KEY" '.[] | select(.key == $key) | .configuration' "$END_TO_END_CONFIG_PATH")
 
         # Navigate to the end-to-end directory
         echo "ℹ️ Navigating to the end-to-end directory..."
         if ! cd ./end-to-end/; then
-          echo "🚨 Failed to navigate to the end-to-end directory."
-          exit 1
+              echo "🚨 Failed to navigate to the end-to-end directory."
+              exit 1
         fi
 
         # After validation, proceed with merging results
         echo "ℹ️ Proceeding with merging results..."
         
         # Extract report_mapping_key values and ensure uniqueness
-        mapping_keys=$(echo "$res" | jq -r '.config[]?.report_mapping_key' | sort -u)
+        mapping_keys=$(echo "$res" | jq -r '.execution[]?.report_mapping_key' | sort -u)
 
         # Add additional keys
         for additional_key in "*ios*" "*android*" "*results*"; do
-          mapping_keys="$mapping_keys"$'\n'"$additional_key"
+              mapping_keys="$mapping_keys"$'\n'"$additional_key"
         done
 
         # Convert mapping_keys into an array by splitting on newlines
@@ -98,132 +104,133 @@ script: |
 
         # Process each key in the array
         for key in "${mapping_keys_array[@]}"; do
-          echo "ℹ️ Processing key: $key"
-          
-          # Split the key into parts using '?' as the delimiter
-          IFS='?' read -ra parts <<< "$key"
+              echo "ℹ️ Processing key: $key"
+              
+              # Split the key into parts using '?' as the delimiter
+              IFS='?' read -ra parts <<< "$key"
 
-          for part in "${parts[@]}"; do
-            # Determine the correct base path and folder name
-            folder_name="${part#\*}"
-            folder_name="${folder_name%\*}"
-            case "$part" in
+              for part in "${parts[@]}"; do
+              # Determine the correct base path and folder name
+              folder_name="${part#\*}"
+              folder_name="${folder_name%\*}"
+              case "$part" in
               *ios*)
-                base_path="./build/reports/wdio-html-nice-reporter-reports"
-                folder_name="ios_platform"
-                ;;
+                    base_path="./build/reports/wdio-html-nice-reporter-reports"
+                    folder_name="ios_platform"
+                    ;;
               *android*)
-                base_path="./build/reports/wdio-html-nice-reporter-reports"
-                folder_name="android_platform"
-                ;;
+                    base_path="./build/reports/wdio-html-nice-reporter-reports"
+                    folder_name="android_platform"
+                    ;;
               *results*)
-                base_path="./build/reports/wdio-html-nice-reporter-reports"
-                folder_name="all_platforms"
-                ;;
+                    base_path="./build/reports/wdio-html-nice-reporter-reports"
+                    folder_name="all_platforms"
+                    ;;
               *)
-                base_path="./build/reports/wdio-html-nice-reporter-reports/teams"
-                ;;
-            esac
+                    base_path="./build/reports/wdio-html-nice-reporter-reports/teams"
+                    ;;
+              esac
 
-          # Start processing
-          echo "ℹ️ Starting the process of merging results..."
+              # Start processing
+              echo "ℹ️ Starting the process of merging results..."
 
-          # Create necessary folders
-          echo "ℹ️ Creating directories..."
-          mkdir -p "$base_path/$folder_name/" || { echo "🚨 Failed to create base folder."; exit 1; }
+              # Create necessary folders
+              echo "ℹ️ Creating directories..."
+              mkdir -p "$base_path/$folder_name/" || { echo "🚨 Failed to create base folder."; exit 1; }
 
-          # Move files to the appropriate directories
-          echo "ℹ️ Moving screenshot files..."
-          mkdir -p ./build/reports/wdio-html-nice-reporter-results/temp/screenshots/ || { echo "🚨 Failed to create temporary screenshot folder."; exit 1; }
-          mv ./build/reports/wdio-html-nice-reporter-results/screenshots/* ./build/reports/wdio-html-nice-reporter-results/temp/screenshots/ || { echo "⚠️ Failed to move screenshots."; }
-          
-          # Merge results
-          echo "ℹ️ Merging results using lib/scripts/mergeResults.js..."
-          
-          if ! node lib/scripts/mergeResults.js ./build/reports/wdio-html-nice-reporter-results/ "$part"; then
+              # Move files to the appropriate directories
+              echo "ℹ️ Moving screenshot files..."
+              mkdir -p ./build/reports/wdio-html-nice-reporter-results/temp/screenshots/ || { echo "🚨 Failed to create temporary screenshot folder."; exit 1; }
+              mv ./build/reports/wdio-html-nice-reporter-results/screenshots/* ./build/reports/wdio-html-nice-reporter-results/temp/screenshots/ || { echo "⚠️ Failed to move screenshots."; }
+              
+              # Merge results
+              echo "ℹ️ Merging results using lib/scripts/mergeResults.js..."
+              
+              if ! node lib/scripts/mergeResults.js ./build/reports/wdio-html-nice-reporter-results/ "$part"; then
               echo "🚨 Failed to merge results. Check lib/scripts/mergeResults.js script."
               exit 1
-          fi
+              fi
 
-          echo "ℹ️ Moving merged report files..."
-          if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/merged-report.html "$base_path/$folder_name/merged-report.html"; then
+              echo "ℹ️ Moving merged report files..."
+              if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/merged-report.html "$base_path/$folder_name/merged-report.html"; then
               echo "🚨 Failed to move wdio-html-nice-reporter-results/temp/merged-report.html"
               exit 1
-          fi
+              fi
 
-          if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/merged-report-no-screenshots.html "$base_path/$folder_name/merged-report-no-screenshots.html"; then
+              if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/merged-report-no-screenshots.html "$base_path/$folder_name/merged-report-no-screenshots.html"; then
               echo "🚨 Failed to move wdio-html-nice-reporter-results/temp/merged-report-no-screenshots.html"
               exit 1
-          fi
+              fi
 
-          if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/merged-report.json "$base_path/$folder_name/merged-report.json"; then
+              if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/merged-report.json "$base_path/$folder_name/merged-report.json"; then
               echo "🚨 Failed to move wdio-html-nice-reporter-results/temp/merged-report.json"
               exit 1
-          fi
+              fi
 
-          if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/glyphicons-halflings-regular.woff "$base_path/$folder_name/glyphicons-halflings-regular.woff"; then
+              if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/glyphicons-halflings-regular.woff "$base_path/$folder_name/glyphicons-halflings-regular.woff"; then
               echo "🚨 Failed to move wdio-html-nice-reporter-results/temp/glyphicons-halflings-regular.woff"
               exit 1
-          fi
+              fi
 
-          if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/report-styles.css "$base_path/$folder_name/report-styles.css"; then
+              if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/report-styles.css "$base_path/$folder_name/report-styles.css"; then
               echo "🚨 Failed to move wdio-html-nice-reporter-results/temp/report-styles.css"
               exit 1
-          fi
+              fi
 
-          if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/master-report.pdf "$base_path/$folder_name/master-report.pdf"; then
-                echo "🚨 Failed to move wdio-html-nice-reporter-results/temp/master-report.pdf"
-                exit 1
-          fi
+              if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/master-report.pdf "$base_path/$folder_name/master-report.pdf"; then
+                    echo "🚨 Failed to move wdio-html-nice-reporter-results/temp/master-report.pdf"
+                    exit 1
+              fi
 
-          if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/master-report-no-screenshots.pdf "$base_path/$folder_name/master-report-no-screenshots.pdf"; then
-                echo "🚨 Failed to move wdio-html-nice-reporter-results/temp/master-report-no-screenshots.pdf"
-                exit 1
-          fi
+              if ! mv ./build/reports/wdio-html-nice-reporter-results/temp/master-report-no-screenshots.pdf "$base_path/$folder_name/master-report-no-screenshots.pdf"; then
+                    echo "🚨 Failed to move wdio-html-nice-reporter-results/temp/master-report-no-screenshots.pdf"
+                    exit 1
+              fi
 
-          # Generate date-based report filenames
-          echo "ℹ️ Generating date-based filenames for reports..."
-          current_date=$(date +'%d-%m-%Y')
+              # Generate date-based report filenames
+              echo "ℹ️ Generating date-based filenames for reports..."
+              current_date=$(date +'%d-%m-%Y')
 
-          if ! mv "$base_path/$folder_name/merged-report.html" "$base_path/$folder_name/$current_date.html"; then
+              if ! mv "$base_path/$folder_name/merged-report.html" "$base_path/$folder_name/$current_date.html"; then
               echo "🚨 Failed to rename $base_path/$folder_name/merged-report.html"
               exit 1
-          fi
+              fi
 
-          if ! mv "$base_path/$folder_name/merged-report-no-screenshots.html" "$base_path/$folder_name/$current_date-no-screenshots.html"; then
+              if ! mv "$base_path/$folder_name/merged-report-no-screenshots.html" "$base_path/$folder_name/$current_date-no-screenshots.html"; then
               echo "🚨 Failed to rename $base_path/$folder_name/merged-report-no-screenshots.html"
               exit 1
-          fi
+              fi
 
-          if ! mv "$base_path/$folder_name/master-report.pdf" "$base_path/$folder_name/$current_date.pdf"; then
+              if ! mv "$base_path/$folder_name/master-report.pdf" "$base_path/$folder_name/$current_date.pdf"; then
               echo "🚨 Failed to rename $base_path/$folder_name/master-report.pdf"
               exit 1
-          fi
+              fi
 
-          if ! mv "$base_path/$folder_name/master-report-no-screenshots.pdf" "$base_path/$folder_name/$current_date-no-screenshots.pdf"; then
+              if ! mv "$base_path/$folder_name/master-report-no-screenshots.pdf" "$base_path/$folder_name/$current_date-no-screenshots.pdf"; then
               echo "🚨 Failed to rename $base_path/$folder_name/master-report-no-screenshots.pdf"
               exit 1
-          fi
+              fi
 
-          # Clean up temporary directory
-          echo "ℹ️ Cleaning up temporary files..."
-          mv ./build/reports/wdio-html-nice-reporter-results/temp/screenshots/* ./build/reports/wdio-html-nice-reporter-results/screenshots/ || { echo "⚠️ Failed to move screenshots."; }
-          rm -rf ./build/reports/wdio-html-nice-reporter-results/temp/ || { echo "🚨 Failed to clean up temporary files."; exit 1; }
+              # Clean up temporary directory
+              echo "ℹ️ Cleaning up temporary files..."
+              mv ./build/reports/wdio-html-nice-reporter-results/temp/screenshots/* ./build/reports/wdio-html-nice-reporter-results/screenshots/ || { echo "⚠️ Failed to move screenshots."; }
+              rm -rf ./build/reports/wdio-html-nice-reporter-results/temp/ || { echo "🚨 Failed to clean up temporary files."; exit 1; }
 
-          echo "ℹ️ Process completed successfully!"
-          done
+              echo "ℹ️ Process completed successfully!"
+              done
         done
 
         if [[ $INVALID_JSON_COUNT -gt 0 ]]; then
-          echo "⚠️ Number of invalid JSON files: $INVALID_JSON_COUNT"
+              echo "⚠️ Number of invalid JSON files: $INVALID_JSON_COUNT"
         else
-          echo "ℹ️ No invalid JSON reported"
+              echo "ℹ️ No invalid JSON reported"
         fi
 
         if [[ $INVALID_BUILDS_COUNT -gt 0 ]]; then
-          echo "⚠️ Number of invalid builds: $INVALID_BUILDS_COUNT"
+              echo "⚠️ Number of invalid builds: $INVALID_BUILDS_COUNT"
+              echo "⚠️ Failed builds: ${failed_builds[*]}"
         else
-          echo "ℹ️ No invalid build(s) reported"
+              echo "ℹ️ No invalid build(s) reported"
         fi
 
         echo "✅ Console reports generated successfully"
@@ -237,24 +244,42 @@ script: |
         find ./build/reports/wdio-html-nice-reporter-reports/ -type f -name "*.pdf" ! -name "*-no-screenshots*.pdf" | zip -q -@ $CM_EXPORT_DIR/_all-reports-PDF.zip
         find ./build/reports/wdio-html-nice-reporter-reports/ -type f -name "*.html" ! -name "*-no-screenshots*.html" | zip -q -@ $CM_EXPORT_DIR/_all-reports-HTML.zip
 
-        # Navigate to the directory containing "teams"
-        cd ./build/reports/wdio-html-nice-reporter-reports/teams || exit
+        find ./build/reports/wdio-html-nice-reporter-results/ -type f | zip -q -@ $CM_EXPORT_DIR/_wdio-html-nice-reporter-results.zip
 
-        # Iterate over each folder inside "teams"
+        # Define the target directory
+        target_dir="./build/reports/wdio-html-nice-reporter-reports/teams"
+
+        # Check if the directory exists
+        if [ ! -d "$target_dir" ]; then
+              echo "❌ Directory $target_dir does not exist. Exiting."
+              exit 0
+        fi
+
+        # Check if the directory contains any subdirectories
+        if [ -z "$(find "$target_dir" -mindepth 1 -type d)" ]; then
+              echo "ℹ️ Directory $target_dir is empty or contains no subdirectories. Skipping zip process."
+              exit 0
+        fi
+
+        echo "ℹ️ Directory $target_dir contains subdirectories. Proceeding with zipping..."
+
+        # Navigate to the directory
+        cd "$target_dir" || exit
+
+        # Iterate over each folder inside the target directory
         for folder in */; do
-          # Remove the trailing slash for the folder name
-          folder_name=$(basename "$folder")
-          
-          # Define the zip file name in the export directory
-          zip_name="teams_${folder_name}.zip"
-          
-          echo "ℹ️ Creating zip for folder: $folder_name -> $zip_name"
-          
-          # Find .pdf files that do not contain "-no-screenshots" and add them to the zip
-          find "$folder" -type f -name "*.pdf" ! -name "*-no-screenshots*" | zip -q -@ "$CM_EXPORT_DIR/$zip_name"
-        done
+              # Remove the trailing slash for the folder name
+              folder_name=$(basename "$folder")
+              
+              # Define the zip file name in the export directory
+              zip_name="teams_${folder_name}.zip"
+              
+              echo "ℹ️ Creating zip for folder per team: $folder_name -> $zip_name"
+              
+              # Find .pdf files that do not contain "-no-screenshots" and add them to the zip
+              find "$folder" -type f -name "*.pdf" ! -name "*-no-screenshots*" | zip -q -@ "$CM_EXPORT_DIR/$zip_name"
+        done 
 
         echo "✅ Zip files created successfully in $CM_EXPORT_DIR."
-        
-        cd ../
+
   fi
diff --git a/SIDI/steps/_e2e_launch_browserstack_builds/codemagic/step.yml b/SIDI/steps/_e2e_launch_browserstack_builds/codemagic/step.yml
--- a/SIDI/steps/_e2e_launch_browserstack_builds/codemagic/step.yml
+++ b/SIDI/steps/_e2e_launch_browserstack_builds/codemagic/step.yml
@@ -8,23 +8,23 @@ script: |
   # Run end-to-end tests if required
   if [[ -n "$RUN_END_TO_END" ]]; then
 
-    # Navigate to the end-to-end directory
-    echo "ℹ️ Navigating to the end-to-end directory..."
-    if ! cd ./end-to-end/; then
-      echo "🚨 Failed to navigate to the end-to-end directory."
-      exit 1
-    fi
+        # Navigate to the end-to-end directory
+        echo "ℹ️ Navigating to the end-to-end directory..."
+        if ! cd ./end-to-end/; then
+        echo "🚨 Failed to navigate to the end-to-end directory."
+        exit 1
+        fi
 
-    # Determine WDIO config path
-    WDIO_CONFIG_PATH="${WDIO_CONFIG_PATH_IOS:-$WDIO_CONFIG_PATH_ANDROID}"
+        # Determine WDIO config path
+        WDIO_CONFIG_PATH="${WDIO_CONFIG_PATH_IOS:-$WDIO_CONFIG_PATH_ANDROID}"
 
-    if [[ "$END_TO_END_BROWSERSTACK_LOCAL_MODE" == "true" ]]; then
+        if [[ "$END_TO_END_BROWSERSTACK_LOCAL_MODE" == "true" ]]; then
         # Setup BrowserStack Local
         BROWSERSTACK_LOCAL_PATH="./build/BrowserStackLocal"
         if [[ ! -f "$BROWSERSTACK_LOCAL_PATH" ]]; then
-          curl -o ./build/BrowserStackLocal.zip "https://www.browserstack.com/browserstack-local/BrowserStackLocal-darwin-x64.zip"
-          unzip -q ./build/BrowserStackLocal.zip -d "build"
-          rm -f ./build/BrowserStackLocal.zip
+              curl -o ./build/BrowserStackLocal.zip "https://www.browserstack.com/browserstack-local/BrowserStackLocal-darwin-x64.zip"
+              unzip -q ./build/BrowserStackLocal.zip -d "build"
+              rm -f ./build/BrowserStackLocal.zip
         fi
 
         # Ensure BrowserStack Local is running
@@ -35,34 +35,51 @@ script: |
         sleep 2
         rm -rf build/temp.command
         echo "✅ BrowserStackLocal is launched."
-    fi
-
-    # Ensure required variables are set
-    required_vars=("WDIO_CONFIG_SPECS" "WDIO_CONFIG_PATH" "BROWSERSTACK_APP_URL" "WDIO_CONFIG_REPORT_NAME")
-    for var in "${required_vars[@]}"; do
-        if [ -z "${!var}" ]; then
-            echo "🚨 Error: Environment variable $var is not set."
-            exit 1
         fi
-    done
 
-    # Process WDIO_CONFIG_SPECS
-    WDIO_CONFIG_SPECS_CORRECT_PATH=$(echo "$WDIO_CONFIG_SPECS" | sed "s/'\\(\\*\\*\\/[^']*\\)'/path.resolve(cleanedPath, '\\1')/g")
+        # Ensure required variables are set
+        required_vars=("WDIO_CONFIG_SPECS" "WDIO_CONFIG_PATH" "BROWSERSTACK_APP_URL" "WDIO_CONFIG_REPORT_NAME" "END_TO_END_CONFIG_KEY" "WDIO_CONFIG_WAIT_FOR_TIMEOUT" "WDIO_CONFIG_CONNECTION_RETRY_TIMEOUT" "WDIO_CONFIG_CONNECTION_RETRY_COUNT" "WDIO_CONFIG_MAX_INSTANCES")
+        for var in "${required_vars[@]}"; do
+        if [ -z "${!var}" ]; then
+              echo "🚨 Error: Environment variable $var is not set."
+              exit 1
+        fi
+        done
 
-    # Determine PLATFORM
-    PLATFORM=${WDIO_CONFIG_PATH_IOS:+ios}
-    PLATFORM=${PLATFORM:-android}
+        # Process WDIO_CONFIG_SPECS
+        WDIO_CONFIG_SPECS_CORRECT_PATH=$(echo "$WDIO_CONFIG_SPECS" | sed "s/'\\(\\*\\*\\/[^']*\\)'/path.resolve(cleanedPath, '\\1')/g")
 
-    # Update WDIO_CONFIG_PATH
-    if [[ -f "$WDIO_CONFIG_PATH" ]]; then
+        # Determine PLATFORM
+        PLATFORM=${WDIO_CONFIG_PATH_IOS:+ios}
+        PLATFORM=${PLATFORM:-android}
+
+        # Handle BrowserStack credentials based on PLATFORM
+        if [[ "$PLATFORM" == "ios" ]]; then
+        if [[ -n "$END_TO_END_BROWSERSTACK_IOS_USER_NAME" ]]; then
+        END_TO_END_BROWSERSTACK_USER_NAME="$END_TO_END_BROWSERSTACK_IOS_USER_NAME"
+        fi
+        if [[ -n "$END_TO_END_BROWSERSTACK_IOS_API_TOKEN" ]]; then
+        END_TO_END_BROWSERSTACK_API_TOKEN="$END_TO_END_BROWSERSTACK_IOS_API_TOKEN"
+        fi
+        elif [[ "$PLATFORM" == "android" ]]; then
+        if [[ -n "$END_TO_END_BROWSERSTACK_ANDROID_USER_NAME" ]]; then
+        END_TO_END_BROWSERSTACK_USER_NAME="$END_TO_END_BROWSERSTACK_ANDROID_USER_NAME"
+        fi
+        if [[ -n "$END_TO_END_BROWSERSTACK_ANDROID_API_TOKEN" ]]; then
+        END_TO_END_BROWSERSTACK_API_TOKEN="$END_TO_END_BROWSERSTACK_ANDROID_API_TOKEN"
+        fi
+        fi
+
+        # Update WDIO_CONFIG_PATH
+        if [[ -f "$WDIO_CONFIG_PATH" ]]; then
         sed "s#process.env.E2E_SPECS_PATTERN#$WDIO_CONFIG_SPECS_CORRECT_PATH#g" "$WDIO_CONFIG_PATH" > "${WDIO_CONFIG_PATH}.tmp" && mv "${WDIO_CONFIG_PATH}.tmp" "$WDIO_CONFIG_PATH"
-    else
+        else
         echo "🚨 Error: WDIO_CONFIG_PATH ($WDIO_CONFIG_PATH) not found."
         exit 1
-    fi
+        fi
 
-    # Define updates for .env.remote
-    env_updates=(
+        # Define updates for .env.remote
+        env_updates=(
         "BS_PATH=$BROWSERSTACK_APP_URL"
         "BUILD_URL=https://codemagic.io/app/$CM_PROJECT_ID/build/$CM_BUILD_ID"
         "BUILD_BRANCH=$CM_BRANCH"
@@ -74,32 +91,36 @@ script: |
         "BS_KEY=$END_TO_END_BROWSERSTACK_API_TOKEN"
         "PROJECT_NAME=$CM_REPO_SLUG"
         "LOCAL_MODE=$END_TO_END_BROWSERSTACK_LOCAL_MODE"
-    )
+        "WAIT_FOR_TIMEOUT=$WDIO_CONFIG_WAIT_FOR_TIMEOUT"
+        "CONNECTION_RETRY_TIMEOUT=$WDIO_CONFIG_CONNECTION_RETRY_TIMEOUT"
+        "CONNECTION_RETRY_COUNT=$WDIO_CONFIG_CONNECTION_RETRY_COUNT"
+        "MAX_INSTANCES=$WDIO_CONFIG_MAX_INSTANCES"
+        )
 
-    # Update configs/.env.remote
-    for update in "${env_updates[@]}"; do
+        # Update configs/.env.remote
+        for update in "${env_updates[@]}"; do
         key=$(echo "$update" | cut -d '=' -f 1)
         value=$(echo "$update" | cut -d '=' -f 2-)
         sed -i.bak -e "s#${key}=#${key}=${value}#g" configs/.env.remote
-    done
+        done
 
-    # Cleanup backup files (optional)
-    rm -f configs/.env.remote.bak
+        # Cleanup backup files (optional)
+        rm -f configs/.env.remote.bak
 
-    echo "✅ Configuration updated successfully."
+        echo "✅ Configuration updated successfully."
 
-    # Export and execute tests
-    cp "$WDIO_CONFIG_PATH" "$CM_EXPORT_DIR"
-    cp configs/.env.remote "$CM_EXPORT_DIR"
-    set -a
-    source configs/.env.remote
-    set +a
+        # Export and execute tests
+        cp "$WDIO_CONFIG_PATH" "$CM_EXPORT_DIR"
+        cp configs/.env.remote "$CM_EXPORT_DIR"
+        set -a
+        source configs/.env.remote
+        set +a
 
-    MAX_RETRIES=3
-    RETRY_DELAY=60
-    attempt=0
+        MAX_RETRIES=3
+        RETRY_DELAY=60
+        attempt=0
 
-    while [[ $attempt -lt $MAX_RETRIES ]]; do
+        while [[ $attempt -lt $MAX_RETRIES ]]; do
         ((attempt++))
         echo "ℹ️ Attempt $attempt of $MAX_RETRIES: Running npx wdio $WDIO_CONFIG_PATH..."
         
@@ -107,32 +128,36 @@ script: |
         output=$(npx wdio "$WDIO_CONFIG_PATH" 2>&1)
         exit_code=$?
 
+        # Failed to create session
+
         # Check for the specific timeout error and startWebDriverSession in the logs
-        if echo "$output" | grep -q "WebDriverError: The operation was aborted due to timeout" && echo "$output" | grep -q "startWebDriverSession"; then
-            echo "⚠️ Timeout detected in logs (startWebDriverSession). Retrying in $RETRY_DELAY seconds..."
-            
-            RESULTS_DIR="./build/reports/wdio-html-nice-reporter-results"
+        if (echo "$output" | grep -q "WebDriverError: The operation was aborted due to timeout" && echo "$output" | grep -q "startWebDriverSession") || 
+              (echo "$output" | grep -q "Error: Failed to create session" && echo "$output" | grep -q "startWebDriverSession"); then
+              echo "⚠️ Timeout or session creation error detected in logs (startWebDriverSession). Retrying in $RETRY_DELAY seconds..."
 
-            # Check if the directory exists
-            if [[ -d "$RESULTS_DIR" ]]; then
-                echo "ℹ️ Deleting all files in $RESULTS_DIR..."
-                rm -f "$RESULTS_DIR"/*
-                echo "✅ All files in $RESULTS_DIR have been deleted."
-            else
-                echo "⚠️ Directory $RESULTS_DIR does not exist. No files to delete."
-            fi
-            sleep $RETRY_DELAY
+              
+              RESULTS_DIR="./build/reports/wdio-html-nice-reporter-results"
+
+              # Check if the directory exists
+              if [[ -d "$RESULTS_DIR" ]]; then
+                    echo "ℹ️ Deleting all files in $RESULTS_DIR..."
+                    rm -f "$RESULTS_DIR"/*
+                    echo "✅ All files in $RESULTS_DIR have been deleted."
+              else
+                    echo "⚠️ Directory $RESULTS_DIR does not exist. No files to delete."
+              fi
+              sleep $RETRY_DELAY
         else
-            # Exit the loop if no specific error was detected (success or other errors)
-            break
+              # Exit the loop if no specific error was detected (success or other errors)
+              break
         fi
-    done
+        done
 
-    if [[ $exit_code -ne 0 ]]; then
+        if [[ $exit_code -ne 0 ]]; then
         echo "🚨 Failed after $MAX_RETRIES attempts. Please check logs for details."
         exit $exit_code
-    else
+        else
         echo "✅ Success on attempt $attempt."
         exit 0
-    fi
+        fi
   fi
diff --git a/SIDI/steps/_e2e_trigger/codemagic/step.yml b/SIDI/steps/_e2e_trigger/codemagic/step.yml
--- a/SIDI/steps/_e2e_trigger/codemagic/step.yml
+++ b/SIDI/steps/_e2e_trigger/codemagic/step.yml
@@ -2,7 +2,7 @@ name: "[END-TO-END] Trigger E2E sessions"
 script: |
   #!/usr/bin/env bash
   # fail if any commands fails
-
+  
   # Avoid usage of run_if
   if [ "$RETRIGGER_WAITING_PREVIOUS_BUILDS" == "true" ]
         then
@@ -39,8 +39,8 @@ script: |
         previous_index=1
   fi
 
-  res=$(jq -c --arg key "$END_TO_END_CONFIG_KEY" '.[] | select(.config_name == $key) | .config_content' "$END_TO_END_CONFIG_PATH")
-  max_index=$(echo "$res" | jq '.config | length')
+  res=$(jq -c --arg key "$END_TO_END_CONFIG_KEY" '.[] | select(.key == $key) | .configuration' "$END_TO_END_CONFIG_PATH")
+  max_index=$(echo "$res" | jq '.execution | length')
   ((max_index=max_index+1))
 
   # Check first where we are in the loop and if it's over
@@ -51,28 +51,28 @@ script: |
               END_TO_END_COLLECT_ARTIFACTS="true"
               echo "END_TO_END_COLLECT_ARTIFACTS=$END_TO_END_COLLECT_ARTIFACTS" >> $CM_ENV
   else
-        res=$(jq -c --arg key "$END_TO_END_CONFIG_KEY" '.[] | select(.config_name == $key) | .config_content' "$END_TO_END_CONFIG_PATH")
+        res=$(jq -c --arg key "$END_TO_END_CONFIG_KEY" '.[] | select(.key == $key) | .configuration' "$END_TO_END_CONFIG_PATH")
         export last_index=1
         loop_index=1
 
         # Set path to wdio config files
-        WDIO_CONFIG_PATH_IOS="$(echo "$res" | jq -c -r '.config_path_ios')"
+        WDIO_CONFIG_PATH_IOS="$(echo "$res" | jq -c -r '.path_ios')"
         echo "WDIO_CONFIG_PATH_IOS=$WDIO_CONFIG_PATH_IOS" >> $CM_ENV
-        WDIO_CONFIG_PATH_ANDROID="$(echo "$res" | jq -c -r '.config_path_android')"
+        WDIO_CONFIG_PATH_ANDROID="$(echo "$res" | jq -c -r '.path_android')"
         echo "WDIO_CONFIG_PATH_ANDROID=$WDIO_CONFIG_PATH_ANDROID" >> $CM_ENV
 
         # Navigate to the end-to-end directory
         echo "ℹ️ Navigating to the end-to-end directory..."
         if ! cd ./end-to-end/; then
-          echo "🚨 Failed to navigate to the end-to-end directory."
-          exit 1
+              echo "🚨 Failed to navigate to the end-to-end directory."
+              exit 1
         fi
         chmod u+x "$WDIO_CONFIG_PATH_IOS"
         chmod u+x "$WDIO_CONFIG_PATH_ANDROID"
 
         # Parse json files
-        echo "$res" | jq -c -r '.config_path_android'
-        echo "$res" | jq -c -r '.config[]' | while read item;
+        echo "$res" | jq -c -r '.path_android'
+        echo "$res" | jq -c -r '.execution[]' | while read item;
         do
               # Load right config based on the index
               if [ $previous_index -le $loop_index ]
