Update doc*.md (#21)
* Bump ansi-regex from 4.1.0 to 4.1.1 (#2)

Bumps [ansi-regex](https://github.com/chalk/ansi-regex) from 4.1.0 to 4.1.1.
- [Release notes](https://github.com/chalk/ansi-regex/releases)
- [Commits](https://github.com/chalk/ansi-regex/compare/v4.1.0...v4.1.1)

---
updated-dependencies:
- dependency-name: ansi-regex
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Bump minimist from 1.2.5 to 1.2.6 (#1)

Bumps [minimist](https://github.com/substack/minimist) from 1.2.5 to 1.2.6.
- [Release notes](https://github.com/substack/minimist/releases)
- [Commits](https://github.com/substack/minimist/compare/1.2.5...1.2.6)

---
updated-dependencies:
- dependency-name: minimist
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Bump follow-redirects from 1.14.7 to 1.15.1 (#3)

Bumps [follow-redirects](https://github.com/follow-redirects/follow-redirects) from 1.14.7 to 1.15.1.
- [Release notes](https://github.com/follow-redirects/follow-redirects/releases)
- [Commits](https://github.com/follow-redirects/follow-redirects/compare/v1.14.7...v1.15.1)

---
updated-dependencies:
- dependency-name: follow-redirects
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Fix #4: add missing json files + bump version

* fix: node version on m1 (#6)

fix nvm for m1

* Update package.json (#7)

* Update step.yml

* Update package.json

* ignore yaml fies automatically

* bump to 3.0.5

* fix profile issue + add cicd support of rn library

* fix github status updater

* Bump sidi-cli to 3.0.6

* Update versionedBranches.md

* Update androidSigning.md

* Update buildTriggers.md

* Update buildTriggers.md

* Update buildTriggers.md

* Update commands.md

* Update customSteps.md

* Update iosCertificates.md

* Update purposedSteps.md

* Update versionedBranches.md

* Update steps.md

* Update workflow.md

* Update androidSigning.md

* Add files via upload

* Update versionedBranches.md

* Add files via upload

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Imran Mnts <imran.mentese@gmail.com>

diff --git a/SIDI/steps/_react_native_pre_build/codemagic/step.yml b/SIDI/steps/_react_native_pre_build/codemagic/step.yml
--- a/SIDI/steps/_react_native_pre_build/codemagic/step.yml
+++ b/SIDI/steps/_react_native_pre_build/codemagic/step.yml
@@ -10,28 +10,24 @@ script: |
 
   echo "PATH=$PATH" >> $CM_ENV
   
-  if [[ $(uname -m) == 'arm64' ]]; then
-    yarn global add node-gyp
-  else
-    # Install NVM
-    PROFILE=$HOME/.profile
-    touch $PROFILE
-    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | PROFILE=$PROFILE bash
-    source $PROFILE
+  # Install NVM
+  PROFILE=$HOME/.profile
+  touch $PROFILE
+  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | PROFILE=$PROFILE bash
+  source $PROFILE
   
-    if [ ! -z "${CM_BUILD_DIR}" ] ; then
-      echo "Switching to working directory: ${CM_BUILD_DIR}"
+  if [ ! -z "${CM_BUILD_DIR}" ] ; then
+    echo "Switching to working directory: ${CM_BUILD_DIR}"
   
-      cd "${CM_BUILD_DIR}"
-      if [ $? -ne 0 ] ; then
-        echo "Failed to switch to working directory: ${CM_BUILD_DIR}"
-      fi
+    cd "${CM_BUILD_DIR}"
+    if [ $? -ne 0 ] ; then
+    echo "Failed to switch to working directory: ${CM_BUILD_DIR}"
     fi
-  
-    # Install latest node version by default
-    if [[ -z "$NODE_VERSION" && ! -e "./.nvmrc" ]]; then NODE_VERSION="node"; fi
-  
-    nvm install ${NODE_VERSION}
-  
-    echo "PATH=$PATH" >> $CM_ENV
   fi
+  
+  # Install latest node version by default
+  if [[ -z "$NODE_VERSION" && ! -e "./.nvmrc" ]]; then NODE_VERSION="node"; fi
+  
+  nvm install ${NODE_VERSION}
+  
+  echo "PATH=$PATH" >> $CM_ENV
